### PR TITLE
Prevent KeyError when response does not have Content-Type

### LINKED ISSUE #364: `response_schema_conformance` check crashes when response does not have a "Content-Type" header
## Current behaviour

When testing against [a teapot server](https://github.com/martinsirbe/go-teapot-server), using the `response_schema_conformance` check raises a `KeyError`.

First, bring up the teapot, this listens on 8080:

```sh
$ docker run --network=host martinsirbe/go-teapot-server:e2223ce
```

Then run the `POST /v3/pet` endpoint of the Petshop schema against the running teapot instance - we expect complete failure:

```sh
$ docker run \
    --network=host \
    kiwicom/schemathesis:v0.23.1 \
    run \
    https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml \
    --base-url http://localhost:8080/ \
    --checks response_schema_conformance \
    --endpoint "/pet$" \
    --method=post
```

But instead of getting failure, we get an error:

```
======================= Schemathesis test session starts =======================
platform Linux -- Python 3.8.1, schemathesis-0.23.1, hypothesis-5.1.5, hypothesis_jsonschema-0.10.2, jsonschema-3.2.0
rootdir: /app
hypothesis profile 'default' -> database=InMemoryExampleDatabase({})
Schema location: https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml
Base URL: http://localhost:8080/
Specification version: Open API 3.0.2
Workers: 1
collected endpoints: 1

POST /v3/pet E                                                           [100%]

==================================== ERRORS ====================================
________________________________ POST: /v3/pet _________________________________
KeyError: 'content-type'

=================================== SUMMARY ====================================

No checks were performed.

============================== 1 errored in 1.10s ==============================
```

## Expected behaviour

The `"Content-Type"` header is not required in HTTP (I had to check this myself and found [this SO post](https://stackoverflow.com/q/20392345/1286705)).

Therefore, Schemathesis checks should be able to handle responses that do not contain the `"Content-Type"` header. The `response_schema_conformance` check can be skipped in this case.

### PR DESCRIPTION
**Pull request by jamescooke**
Fixes #364

### CODE REVIEW

**Comment by Stranger6667** [comment]
Thank you @jamescooke :) I'll fix the build and merge it

**Comment by Stranger6667** [comment]
The fix is released in `0.23.2` - https://pypi.org/project/schemathesis/0.23.2/

**Comment by jamescooke** [comment]
@Stranger6667 Thanks for the quick merge :+1: 

Can you help me understand what was wrong with the build? Did I break something?

**Comment by Stranger6667** [comment]
You are very welcome! :)

There were two things:
- `pydocstyle` complained about docstring formatting with D205, D212, D400, D415 (more info - http://www.pydocstyle.org/en/2.1.1/error_codes.html)
- Codecov token is not shared with forks and the build failed on uploading coverage to codecov.io. I am not sure how to solve this problem :( Repo where the code is should have `CODECOV_TOKEN` in its settings. 

@svtkachenko do you remember any options to solve the issue with tokens?

**Comment by jamescooke** [comment]
Ahh OK - I can see now. On this build for example: https://github.com/kiwicom/schemathesis/runs/393629329

> Please provide an upload token from codecov.io with valid arguments

I'll keep an eye open for this in the future.

I thought it was a problem with a failing test because this test https://github.com/kiwicom/schemathesis/blob/f9b43ca8bbe159a91e85e17196f56044d24e22c6/test/test_hypothesis.py#L143-L162 was failing on my system locally for some reason. It seems like it was being flaky because it worked on push and is now working locally again. :man_shrugging:

**Pull request merged**
