### PR TITLE
update importlib pin and regenerate poetry lock

### LINKED ISSUE #314: loosen importlib metadata pin
https://github.com/kiwicom/schemathesis/blob/3542d91d2e7402235e7b2dc995ed7017a0265ff6/pyproject.toml#L37

while pulling in schemathesis
 as a new dependency(cause it does great things) we noted a conflict

`pkg_resources.ContextualVersionConflict: (importlib-metadata 1.1.0 (/var/lib/jenkins/workspace/$REDACTED/py-venv/lib/python3.6/site-packages), Requirement.parse('importlib_metadata<0.24.0,>=0.23.0'), {'schemathesis'})`

i believe it should e relatively safe to unpin or at least switch to the 1.x series

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
fixes #314 

with this pin i update to the importlib_metadata 1.1 series,
i''m experimenting with some finer details on poetry version pins before un-wip-ing

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@Stranger6667 as  far as i can tell the failures relate to codecov tokens not being exposed to my PR

any eta on when the changes can be in and up for release

**Comment by Stranger6667** [comment]
Thank you for the PR @RonnyPfannschmidt !
Will do a new release in a few minutes

**Comment by Stranger6667** [comment]
Released - https://pypi.org/project/schemathesis/0.19.0/

**Comment by RonnyPfannschmidt** [comment]
@Stranger6667 awesome, thanks for the swift release, saves part of my day

**Comment by Stranger6667** [comment]
Thank you @RonnyPfannschmidt for bringing it up :)

**Pull request merged**
